import { LEGACY_COURSE_SLUG_ALIASES } from "./seed-types";
import type { CourseSeed, CourseSeedFile, HoleSeed, LayoutSeed } from "./seed-types";
import type { LoadedSeedFile } from "./list-seed-files";

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNullableText(value: string | null): string {
  return value === null ? "null" : sqlString(value);
}

function sqlNullableNumber(value: number | null): string {
  return value === null ? "null" : String(value);
}

function sqlBoolean(value: boolean): string {
  return value ? "true" : "false";
}

function legacySlugAlignmentSql(): string {
  const statements: string[] = [];

  for (const [canonicalSlug, aliases] of Object.entries(LEGACY_COURSE_SLUG_ALIASES)) {
    for (const alias of aliases) {
      statements.push(
        `update public.courses set slug = ${sqlString(canonicalSlug)} where slug = ${sqlString(alias)};`,
      );
    }
  }

  return statements.join("\n");
}

function courseUpsertSql(course: CourseSeed): string {
  return `insert into public.courses (
  name, location, slug, lat, lng, details, terrain_type, difficulty_tier, source_url
) values (
  ${sqlString(course.name)},
  ${sqlString(course.location)},
  ${sqlString(course.slug)},
  ${sqlNullableNumber(course.lat)},
  ${sqlNullableNumber(course.lng)},
  ${sqlNullableText(course.details)},
  ${sqlNullableText(course.terrain_type)},
  ${sqlNullableText(course.difficulty_tier)},
  ${sqlNullableText(course.source_url ?? null)}
)
on conflict (slug) do update set
  name = excluded.name,
  location = excluded.location,
  lat = excluded.lat,
  lng = excluded.lng,
  details = excluded.details,
  terrain_type = excluded.terrain_type,
  difficulty_tier = excluded.difficulty_tier,
  source_url = excluded.source_url;`;
}

function layoutUpsertSql(courseSlug: string, layout: LayoutSeed): string {
  return `insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  ${sqlString(layout.name)},
  ${layout.total_par},
  ${layout.total_distance_m},
  ${sqlString(layout.slug)},
  ${sqlNullableText(layout.map_url)},
  ${sqlBoolean(layout.is_active)}
from public.courses c
where c.slug = ${sqlString(courseSlug)}
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;`;
}

function holeValueRow(hole: HoleSeed): string {
  return `  (${hole.hole_number}, ${hole.par}, ${hole.distance_m}, ${sqlNullableText(hole.notes)}, ${sqlNullableText(hole.hole_map_url)})`;
}

function holesUpsertSql(courseSlug: string, layoutSlug: string, holes: HoleSeed[]): string {
  const values = holes.map(holeValueRow).join(",\n");

  return `insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
${values}
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = ${sqlString(courseSlug)}
  and l.slug = ${sqlString(layoutSlug)}
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;`;
}

function layoutSectionSql(seed: CourseSeedFile, label: string): string {
  return `-- ${label}: ${seed.course.slug} / ${seed.layout.slug}
${layoutUpsertSql(seed.course.slug, seed.layout)}
${holesUpsertSql(seed.course.slug, seed.layout.slug, seed.holes)}`;
}

export function generateCourseSeedSql(loaded: LoadedSeedFile[]): string {
  const coursesBySlug = new Map<string, CourseSeed>();
  for (const { data } of loaded) {
    coursesBySlug.set(data.course.slug, data.course);
  }

  const header = `-- Generated by: npm run seed:courses
-- Source: supabase/seeds/courses/*.json
-- Idempotent upserts. Safe to re-apply via Supabase CLI.
`;

  const parts = [
    header,
    legacySlugAlignmentSql(),
    "",
    "-- courses",
    ...[...coursesBySlug.values()].map(courseUpsertSql),
    "",
    "-- layouts + holes",
    ...loaded.map(({ data, label }) => layoutSectionSql(data, label)),
  ];

  return `${parts.filter((part) => part.length > 0).join("\n\n")}\n`;
}
