-- Generated by: npm run seed:courses
-- Source: supabase/seeds/courses/*.json
-- Idempotent upserts. Safe to re-apply via Supabase CLI.


update public.courses set slug = 'jarve-discgolfipark' where slug = 'jarve';

-- courses

insert into public.courses (
  name, location, slug, lat, lng, details, terrain_type, difficulty_tier, source_url
) values (
  'Haapsalu',
  'Haapsalu, Läänemaa, Estonia',
  'haapsalu',
  null,
  null,
  null,
  null,
  null,
  null
)
on conflict (slug) do update set
  name = excluded.name,
  location = excluded.location,
  lat = excluded.lat,
  lng = excluded.lng,
  details = excluded.details,
  terrain_type = excluded.terrain_type,
  difficulty_tier = excluded.difficulty_tier,
  source_url = excluded.source_url;

insert into public.courses (
  name, location, slug, lat, lng, details, terrain_type, difficulty_tier, source_url
) values (
  'Järve discgolfipark',
  'Tallinn, Kesklinn, Harjumaa, Estonia',
  'jarve-discgolfipark',
  null,
  null,
  null,
  null,
  null,
  null
)
on conflict (slug) do update set
  name = excluded.name,
  location = excluded.location,
  lat = excluded.lat,
  lng = excluded.lng,
  details = excluded.details,
  terrain_type = excluded.terrain_type,
  difficulty_tier = excluded.difficulty_tier,
  source_url = excluded.source_url;

insert into public.courses (
  name, location, slug, lat, lng, details, terrain_type, difficulty_tier, source_url
) values (
  'Keila discgolfpark',
  'Keila, Harjumaa, Estonia',
  'keila-discgolfpark',
  null,
  null,
  null,
  null,
  null,
  null
)
on conflict (slug) do update set
  name = excluded.name,
  location = excluded.location,
  lat = excluded.lat,
  lng = excluded.lng,
  details = excluded.details,
  terrain_type = excluded.terrain_type,
  difficulty_tier = excluded.difficulty_tier,
  source_url = excluded.source_url;

insert into public.courses (
  name, location, slug, lat, lng, details, terrain_type, difficulty_tier, source_url
) values (
  'Kohila',
  'Kohila, Raplamaa, Estonia',
  'kohila',
  null,
  null,
  null,
  null,
  null,
  null
)
on conflict (slug) do update set
  name = excluded.name,
  location = excluded.location,
  lat = excluded.lat,
  lng = excluded.lng,
  details = excluded.details,
  terrain_type = excluded.terrain_type,
  difficulty_tier = excluded.difficulty_tier,
  source_url = excluded.source_url;

insert into public.courses (
  name, location, slug, lat, lng, details, terrain_type, difficulty_tier, source_url
) values (
  'Kurna discgolfipark',
  'Kurna, Harjumaa, Estonia',
  'kurna-discgolfipark',
  null,
  null,
  null,
  null,
  null,
  null
)
on conflict (slug) do update set
  name = excluded.name,
  location = excluded.location,
  lat = excluded.lat,
  lng = excluded.lng,
  details = excluded.details,
  terrain_type = excluded.terrain_type,
  difficulty_tier = excluded.difficulty_tier,
  source_url = excluded.source_url;

insert into public.courses (
  name, location, slug, lat, lng, details, terrain_type, difficulty_tier, source_url
) values (
  'Maardu',
  'Maardu, Harjumaa, Estonia',
  'maardu',
  null,
  null,
  null,
  null,
  null,
  null
)
on conflict (slug) do update set
  name = excluded.name,
  location = excluded.location,
  lat = excluded.lat,
  lng = excluded.lng,
  details = excluded.details,
  terrain_type = excluded.terrain_type,
  difficulty_tier = excluded.difficulty_tier,
  source_url = excluded.source_url;

insert into public.courses (
  name, location, slug, lat, lng, details, terrain_type, difficulty_tier, source_url
) values (
  'Männiku Wakepark',
  'Saku, Männiku, Harjumaa, Estonia',
  'manniku-wakepark',
  null,
  null,
  null,
  null,
  null,
  null
)
on conflict (slug) do update set
  name = excluded.name,
  location = excluded.location,
  lat = excluded.lat,
  lng = excluded.lng,
  details = excluded.details,
  terrain_type = excluded.terrain_type,
  difficulty_tier = excluded.difficulty_tier,
  source_url = excluded.source_url;

insert into public.courses (
  name, location, slug, lat, lng, details, terrain_type, difficulty_tier, source_url
) values (
  'Muraste',
  'Muraste, Harjumaa, Estonia',
  'muraste',
  null,
  null,
  null,
  null,
  null,
  null
)
on conflict (slug) do update set
  name = excluded.name,
  location = excluded.location,
  lat = excluded.lat,
  lng = excluded.lng,
  details = excluded.details,
  terrain_type = excluded.terrain_type,
  difficulty_tier = excluded.difficulty_tier,
  source_url = excluded.source_url;

insert into public.courses (
  name, location, slug, lat, lng, details, terrain_type, difficulty_tier, source_url
) values (
  'Nõva discgolfipark',
  'Nõva, Läänemaa, Estonia',
  'nova-discgolfipark',
  null,
  null,
  null,
  null,
  null,
  null
)
on conflict (slug) do update set
  name = excluded.name,
  location = excluded.location,
  lat = excluded.lat,
  lng = excluded.lng,
  details = excluded.details,
  terrain_type = excluded.terrain_type,
  difficulty_tier = excluded.difficulty_tier,
  source_url = excluded.source_url;

insert into public.courses (
  name, location, slug, lat, lng, details, terrain_type, difficulty_tier, source_url
) values (
  'Pirgu',
  'Pirgu, Raplamaa, Estonia',
  'pirgu',
  null,
  null,
  null,
  null,
  null,
  null
)
on conflict (slug) do update set
  name = excluded.name,
  location = excluded.location,
  lat = excluded.lat,
  lng = excluded.lng,
  details = excluded.details,
  terrain_type = excluded.terrain_type,
  difficulty_tier = excluded.difficulty_tier,
  source_url = excluded.source_url;

insert into public.courses (
  name, location, slug, lat, lng, details, terrain_type, difficulty_tier, source_url
) values (
  'Vasalemma',
  'Vasalemma, Harjumaa, Estonia',
  'vasalemma',
  null,
  null,
  null,
  null,
  null,
  null
)
on conflict (slug) do update set
  name = excluded.name,
  location = excluded.location,
  lat = excluded.lat,
  lng = excluded.lng,
  details = excluded.details,
  terrain_type = excluded.terrain_type,
  difficulty_tier = excluded.difficulty_tier,
  source_url = excluded.source_url;

insert into public.courses (
  name, location, slug, lat, lng, details, terrain_type, difficulty_tier, source_url
) values (
  'Viimsi discgolfipark',
  'Viimsi, Harjumaa, Estonia',
  'viimsi-discgolfipark',
  null,
  null,
  null,
  null,
  null,
  null
)
on conflict (slug) do update set
  name = excluded.name,
  location = excluded.location,
  lat = excluded.lat,
  lng = excluded.lng,
  details = excluded.details,
  terrain_type = excluded.terrain_type,
  difficulty_tier = excluded.difficulty_tier,
  source_url = excluded.source_url;

-- layouts + holes

-- haapsalu-moisaharra-sojaretk.json: haapsalu / moisaharra-sojaretk-must
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  'Mõisahärra sõjaretk (must)',
  58,
  1768,
  'moisaharra-sojaretk-must',
  null,
  true
from public.courses c
where c.slug = 'haapsalu'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 3, 70, null, null),
  (2, 3, 68, null, null),
  (3, 4, 180, null, null),
  (4, 3, 90, null, null),
  (5, 3, 93, null, null),
  (6, 3, 84, null, null),
  (7, 3, 104, null, null),
  (8, 3, 84, null, null),
  (9, 4, 128, null, null),
  (10, 4, 131, null, null),
  (11, 3, 70, null, null),
  (12, 3, 77, null, null),
  (13, 3, 80, null, null),
  (14, 3, 98, null, null),
  (15, 4, 181, null, null),
  (16, 3, 85, null, null),
  (17, 3, 72, null, null),
  (18, 3, 73, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'haapsalu'
  and l.slug = 'moisaharra-sojaretk-must'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- haapsalu-moisaproua-jalutuskaik.json: haapsalu / moisaproua-jalutuskaik-punane
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  'Mõisaproua jalutuskäik (punane)',
  56,
  1511,
  'moisaproua-jalutuskaik-punane',
  null,
  true
from public.courses c
where c.slug = 'haapsalu'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 3, 68, null, null),
  (2, 3, 72, null, null),
  (3, 3, 54, null, null),
  (4, 3, 95, null, null),
  (5, 3, 92, null, null),
  (6, 3, 83, null, null),
  (7, 3, 104, null, null),
  (8, 3, 50, null, null),
  (9, 3, 65, null, null),
  (10, 3, 80, null, null),
  (11, 3, 67, null, null),
  (12, 3, 79, null, null),
  (13, 3, 82, null, null),
  (14, 3, 98, null, null),
  (15, 5, 188, null, null),
  (16, 3, 88, null, null),
  (17, 3, 73, null, null),
  (18, 3, 73, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'haapsalu'
  and l.slug = 'moisaproua-jalutuskaik-punane'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- haapsalu-paruni-talvetee-sinine.json: haapsalu / paruni-talvetee-sinine
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  'Paruni talvetee (sinine)',
  60,
  1516,
  'paruni-talvetee-sinine',
  null,
  true
from public.courses c
where c.slug = 'haapsalu'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 3, 70, null, null),
  (2, 3, 70, null, null),
  (3, 3, 65, null, null),
  (4, 3, 94, null, null),
  (5, 3, 82, null, null),
  (6, 3, 67, null, null),
  (7, 3, 78, null, null),
  (8, 3, 82, null, null),
  (9, 3, 75, null, null),
  (10, 3, 73, null, null),
  (11, 3, 70, null, null),
  (12, 3, 70, null, null),
  (13, 3, 65, null, null),
  (14, 3, 94, null, null),
  (15, 3, 82, null, null),
  (16, 3, 67, null, null),
  (17, 3, 78, null, null),
  (18, 3, 82, null, null),
  (19, 3, 75, null, null),
  (20, 3, 77, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'haapsalu'
  and l.slug = 'paruni-talvetee-sinine'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- jarve-discgolfipark-algaja-7.json: jarve-discgolfipark / algaja-7
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  'Algaja 7',
  21,
  307,
  'algaja-7',
  null,
  true
from public.courses c
where c.slug = 'jarve-discgolfipark'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 3, 55, null, null),
  (2, 3, 43, null, null),
  (3, 3, 46, null, null),
  (4, 3, 33, null, null),
  (5, 3, 41, null, null),
  (6, 3, 39, null, null),
  (7, 3, 50, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'jarve-discgolfipark'
  and l.slug = 'algaja-7'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- jarve-discgolfipark-am-18-2026.json: jarve-discgolfipark / am-18-2026
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  'AM 18 2026',
  62,
  1820,
  'am-18-2026',
  null,
  true
from public.courses c
where c.slug = 'jarve-discgolfipark'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 4, 130, null, null),
  (2, 3, 88, null, null),
  (3, 4, 119, null, null),
  (4, 3, 78, null, null),
  (5, 3, 71, null, null),
  (6, 3, 85, null, null),
  (7, 4, 128, null, null),
  (8, 3, 79, null, null),
  (9, 3, 102, null, null),
  (10, 4, 122, null, null),
  (11, 4, 119, null, null),
  (12, 3, 72, null, null),
  (13, 4, 119, null, null),
  (14, 3, 83, null, null),
  (15, 3, 82, null, null),
  (16, 4, 134, null, null),
  (17, 4, 133, null, null),
  (18, 3, 76, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'jarve-discgolfipark'
  and l.slug = 'am-18-2026'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- jarve-discgolfipark-pro-18-2026.json: jarve-discgolfipark / pro-18-2026
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  'Pro 18 2026',
  62,
  2211,
  'pro-18-2026',
  null,
  true
from public.courses c
where c.slug = 'jarve-discgolfipark'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 4, 163, null, null),
  (2, 3, 88, null, null),
  (3, 4, 145, null, null),
  (4, 3, 99, null, null),
  (5, 3, 92, null, null),
  (6, 3, 107, null, null),
  (7, 4, 175, null, null),
  (8, 3, 79, null, null),
  (9, 3, 102, null, null),
  (10, 4, 168, null, null),
  (11, 4, 128, null, null),
  (12, 3, 97, null, null),
  (13, 4, 148, null, null),
  (14, 3, 102, null, null),
  (15, 3, 105, null, null),
  (16, 4, 169, null, null),
  (17, 4, 155, null, null),
  (18, 3, 89, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'jarve-discgolfipark'
  and l.slug = 'pro-18-2026'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- keila-discgolfpark-harrastaja-2026.json: keila-discgolfpark / harrastaja-2026
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  'Harrastaja 2026',
  66,
  1926,
  'harrastaja-2026',
  null,
  true
from public.courses c
where c.slug = 'keila-discgolfpark'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 3, 72, null, null),
  (2, 3, 85, null, null),
  (3, 3, 96, null, null),
  (4, 3, 87, null, null),
  (5, 3, 70, null, null),
  (6, 4, 152, null, null),
  (7, 3, 105, null, null),
  (8, 4, 120, null, null),
  (9, 3, 82, null, null),
  (10, 3, 85, null, null),
  (11, 3, 93, null, null),
  (12, 3, 87, null, null),
  (13, 4, 118, null, null),
  (14, 3, 66, null, null),
  (15, 3, 101, null, null),
  (16, 3, 99, null, null),
  (17, 3, 111, null, null),
  (18, 3, 91, null, null),
  (19, 3, 82, null, null),
  (20, 3, 50, null, null),
  (21, 3, 74, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'keila-discgolfpark'
  and l.slug = 'harrastaja-2026'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- keila-discgolfpark-pro-2026.json: keila-discgolfpark / pro-2026
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  'Pro 2026',
  60,
  2155,
  'pro-2026',
  null,
  true
from public.courses c
where c.slug = 'keila-discgolfpark'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 3, 72, null, null),
  (2, 4, 212, null, null),
  (3, 4, 169, null, null),
  (4, 4, 152, null, null),
  (5, 3, 105, null, null),
  (6, 4, 158, null, null),
  (7, 3, 82, null, null),
  (8, 3, 98, null, null),
  (9, 4, 189, null, null),
  (10, 4, 172, null, null),
  (11, 3, 66, null, null),
  (12, 3, 113, null, null),
  (13, 3, 99, null, null),
  (14, 3, 111, null, null),
  (15, 3, 125, null, null),
  (16, 3, 82, null, null),
  (17, 3, 50, null, null),
  (18, 3, 100, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'keila-discgolfpark'
  and l.slug = 'pro-2026'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- kohila-19-2025.json: kohila / 19-2025
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  '19 korvi 2025',
  59,
  2041,
  '19-2025',
  null,
  true
from public.courses c
where c.slug = 'kohila'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 4, 180, null, null),
  (2, 3, 99, null, null),
  (3, 3, 115, null, null),
  (4, 3, 50, null, null),
  (5, 4, 158, null, null),
  (6, 3, 130, null, null),
  (7, 3, 125, null, null),
  (8, 3, 117, null, null),
  (9, 3, 103, null, null),
  (10, 3, 105, null, null),
  (11, 3, 82, null, null),
  (12, 3, 137, null, null),
  (13, 3, 97, null, null),
  (14, 3, 75, null, null),
  (15, 3, 96, null, null),
  (16, 3, 85, null, null),
  (17, 3, 109, null, null),
  (18, 3, 108, null, null),
  (19, 3, 70, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'kohila'
  and l.slug = '19-2025'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- kurna-discgolfipark-2024.json: kurna-discgolfipark / 2024
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  '2024',
  56,
  1555,
  '2024',
  null,
  true
from public.courses c
where c.slug = 'kurna-discgolfipark'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 3, 97, null, null),
  (2, 3, 70, null, null),
  (3, 3, 58, null, null),
  (4, 4, 121, null, null),
  (5, 3, 92, null, null),
  (6, 3, 80, null, null),
  (7, 3, 77, null, null),
  (8, 3, 114, null, null),
  (9, 3, 76, null, null),
  (10, 3, 82, null, null),
  (11, 3, 63, null, null),
  (12, 3, 78, null, null),
  (13, 3, 54, null, null),
  (14, 3, 86, null, null),
  (15, 3, 92, null, null),
  (16, 3, 94, null, null),
  (17, 3, 77, null, null),
  (18, 4, 144, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'kurna-discgolfipark'
  and l.slug = '2024'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- maardu-am-2025.json: maardu / am-2025
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  'AM 2025',
  70,
  1919,
  'am-2025',
  null,
  true
from public.courses c
where c.slug = 'maardu'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 4, 108, null, null),
  (2, 3, 95, null, null),
  (3, 3, 70, null, null),
  (4, 3, 83, null, null),
  (5, 4, 127, null, null),
  (6, 3, 75, null, null),
  (7, 3, 94, null, null),
  (8, 3, 97, null, null),
  (9, 3, 83, null, null),
  (10, 4, 120, null, null),
  (11, 4, 93, null, null),
  (12, 3, 93, null, null),
  (13, 3, 91, null, null),
  (14, 3, 76, null, null),
  (15, 3, 60, null, null),
  (16, 3, 86, null, null),
  (17, 3, 75, null, null),
  (18, 3, 96, null, null),
  (19, 3, 91, null, null),
  (20, 3, 85, null, null),
  (21, 3, 76, null, null),
  (22, 3, 45, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'maardu'
  and l.slug = 'am-2025'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- maardu-pro-2025.json: maardu / pro-2025
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  'Pro 2025',
  60,
  2353,
  'pro-2025',
  null,
  true
from public.courses c
where c.slug = 'maardu'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 4, 138, null, null),
  (2, 3, 117, null, null),
  (3, 3, 107, null, null),
  (4, 3, 124, null, null),
  (5, 3, 87, null, null),
  (6, 3, 96, null, null),
  (7, 3, 138, null, null),
  (8, 3, 122, null, null),
  (9, 4, 174, null, null),
  (10, 5, 210, null, null),
  (11, 4, 191, null, null),
  (12, 3, 103, null, null),
  (13, 3, 80, null, null),
  (14, 3, 108, null, null),
  (15, 4, 182, null, null),
  (16, 3, 150, null, null),
  (17, 3, 106, null, null),
  (18, 3, 120, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'maardu'
  and l.slug = 'pro-2025'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- manniku-wakepark-2026.json: manniku-wakepark / 2026
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  '2026',
  77,
  2292,
  '2026',
  null,
  true
from public.courses c
where c.slug = 'manniku-wakepark'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 4, 129, null, null),
  (2, 4, 124, null, null),
  (3, 3, 76, null, null),
  (4, 5, 174, null, null),
  (5, 3, 79, null, null),
  (6, 4, 161, null, null),
  (7, 4, 100, null, null),
  (8, 4, 123, null, null),
  (9, 3, 67, null, null),
  (10, 3, 57, null, null),
  (11, 3, 79, null, null),
  (12, 3, 69, null, null),
  (13, 3, 90, null, null),
  (14, 4, 132, null, null),
  (15, 3, 71, null, null),
  (16, 3, 68, null, null),
  (17, 4, 111, null, null),
  (18, 4, 139, null, null),
  (19, 4, 139, null, null),
  (20, 4, 127, null, null),
  (21, 5, 177, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'manniku-wakepark'
  and l.slug = '2026'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- muraste-2026.json: muraste / 2026
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  '2026',
  58,
  1843,
  '2026',
  null,
  true
from public.courses c
where c.slug = 'muraste'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 3, 80, null, null),
  (2, 4, 172, null, null),
  (3, 4, 171, null, null),
  (4, 4, 170, null, null),
  (5, 4, 162, null, null),
  (6, 3, 77, null, null),
  (7, 3, 76, null, null),
  (8, 3, 103, null, null),
  (9, 3, 71, null, null),
  (10, 3, 69, null, null),
  (11, 3, 117, null, null),
  (12, 3, 63, null, null),
  (13, 3, 93, null, null),
  (14, 3, 60, null, null),
  (15, 3, 58, null, null),
  (16, 3, 111, null, null),
  (17, 3, 103, null, null),
  (18, 3, 87, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'muraste'
  and l.slug = '2026'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- nova-discgolfipark-18-korvi.json: nova-discgolfipark / 18-korvi
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  '18 korvi',
  55,
  1351,
  '18-korvi',
  null,
  true
from public.courses c
where c.slug = 'nova-discgolfipark'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 3, 65, null, null),
  (2, 3, 63, null, null),
  (3, 3, 72, null, null),
  (4, 3, 80, null, null),
  (5, 3, 69, null, null),
  (6, 3, 91, null, null),
  (7, 3, 68, null, null),
  (8, 3, 67, null, null),
  (9, 3, 76, null, null),
  (10, 4, 143, null, null),
  (11, 3, 70, null, null),
  (12, 3, 57, null, null),
  (13, 3, 75, null, null),
  (14, 3, 58, null, null),
  (15, 3, 70, null, null),
  (16, 3, 55, null, null),
  (17, 3, 92, null, null),
  (18, 3, 80, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'nova-discgolfipark'
  and l.slug = '18-korvi'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- pirgu-18-korvi.json: pirgu / 18-korvi
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  '18 korvi',
  54,
  1474,
  '18-korvi',
  null,
  true
from public.courses c
where c.slug = 'pirgu'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 3, 96, null, null),
  (2, 3, 91, null, null),
  (3, 3, 71, null, null),
  (4, 3, 78, null, null),
  (5, 3, 66, null, null),
  (6, 3, 82, null, null),
  (7, 3, 75, null, null),
  (8, 3, 88, null, null),
  (9, 3, 84, null, null),
  (10, 3, 73, null, null),
  (11, 3, 76, null, null),
  (12, 3, 64, null, null),
  (13, 3, 47, null, null),
  (14, 3, 134, null, null),
  (15, 3, 79, null, null),
  (16, 3, 83, null, null),
  (17, 3, 84, null, null),
  (18, 3, 103, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'pirgu'
  and l.slug = '18-korvi'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- vasalemma-22-2025.json: vasalemma / 22-2025
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  '22 korvi 2025',
  69,
  1365,
  '22-2025',
  null,
  true
from public.courses c
where c.slug = 'vasalemma'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 4, 99, null, null),
  (2, 3, 71, null, null),
  (3, 3, 63, null, null),
  (4, 4, 136, null, null),
  (5, 3, 50, null, null),
  (6, 3, 56, null, null),
  (7, 3, 49, null, null),
  (8, 3, 41, null, null),
  (9, 3, 52, null, null),
  (10, 3, 57, null, null),
  (11, 4, 65, null, null),
  (12, 3, 40, null, null),
  (13, 3, 75, null, null),
  (14, 3, 58, null, null),
  (15, 3, 67, null, null),
  (16, 3, 70, null, null),
  (17, 3, 60, null, null),
  (18, 3, 61, null, null),
  (19, 3, 41, null, null),
  (20, 3, 58, null, null),
  (21, 3, 47, null, null),
  (22, 3, 49, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'vasalemma'
  and l.slug = '22-2025'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;

-- viimsi-discgolfipark-2025.json: viimsi-discgolfipark / 2025
insert into public.layouts (
  course_id, name, total_par, total_distance_m, slug, map_url, is_active
)
select
  c.id,
  '2025',
  58,
  1687,
  '2025',
  null,
  true
from public.courses c
where c.slug = 'viimsi-discgolfipark'
on conflict (course_id, slug) do update set
  name = excluded.name,
  total_par = excluded.total_par,
  total_distance_m = excluded.total_distance_m,
  map_url = excluded.map_url,
  is_active = excluded.is_active;
insert into public.holes (
  layout_id, hole_number, par, distance_m, notes, hole_map_url
)
select
  l.id,
  v.hole_number,
  v.par,
  v.distance_m,
  v.notes,
  v.hole_map_url
from public.layouts l
join public.courses c on l.course_id = c.id
cross join (
values
  (1, 3, 55, null, null),
  (2, 3, 83, null, null),
  (3, 3, 58, null, null),
  (4, 3, 99, null, null),
  (5, 3, 112, null, null),
  (6, 4, 136, null, null),
  (7, 4, 153, null, null),
  (8, 3, 79, null, null),
  (9, 4, 135, null, null),
  (10, 3, 80, null, null),
  (11, 4, 170, null, null),
  (12, 3, 50, null, null),
  (13, 3, 108, null, null),
  (14, 3, 83, null, null),
  (15, 3, 74, null, null),
  (16, 3, 63, null, null),
  (17, 3, 71, null, null),
  (18, 3, 78, null, null)
) as v(hole_number, par, distance_m, notes, hole_map_url)
where c.slug = 'viimsi-discgolfipark'
  and l.slug = '2025'
on conflict (layout_id, hole_number) do update set
  par = excluded.par,
  distance_m = excluded.distance_m,
  notes = excluded.notes,
  hole_map_url = excluded.hole_map_url;
